const mealItems = [
  {
    id: 1,
    img: "/image/1-2-food-free-png-image.png",
    name: "French Fries",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 2,
    img: "/image/image1.jpg",
    name: "Burger",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 3,
    img: "/image/image2.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 4,
    img: "/image/image3.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 5,
    img: "/image/image4.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 6,
    img: "/image/image5.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 7,
    img: "/image/image6.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 8,
    img: "/image/image7.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 9,
    img: "/image/image8.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 10,
    img: "/image/Screenshot_20221210_110702.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: 11,
    img: "/image/Screenshot_20221210_110820.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
];

export default mealItems;
