const mealItems = [
  {
    id: Math.random(),
    img: "/image/1-2-food-free-png-image.png",
    name: "French Fries",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image1.jpg",
    name: "Burger",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image2.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image3.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image4.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image5.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image6.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image7.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/image8.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/Screenshot_20221210_110702.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
  {
    id: Math.random(),
    img: "/image/Screenshot_20221210_110820.jpg",
    name: "Egusi",
    description: "loram ipsum dlor sit amet, consectetur adipiscing elit upla",
    price: 2700,
    tag: "Lunch",
  },
];

export default mealItems;
